/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package idcardgenerator;

import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Toolkit;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Win7
 */
public class IdCard extends javax.swing.JFrame{

    /**
     * Creates new form IdCard
     */
    public IdCard() {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
    }
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pPanel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        cardName = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        dbId = new javax.swing.JLabel();
        stdId = new javax.swing.JLabel();
        imgId = new javax.swing.JLabel();
        emailId = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        bldId = new javax.swing.JLabel();
        genId = new javax.swing.JLabel();
        gendID = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        addID = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cardBranch = new javax.swing.JLabel();
        cardMob = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        Back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(1080, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, -1, -1));

        pPanel.setForeground(new java.awt.Color(255, 255, 255));
        pPanel.setMinimumSize(new java.awt.Dimension(0, 0));
        pPanel.setOpaque(false);
        pPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setMaximumSize(new java.awt.Dimension(250, 350));
        jPanel3.setMinimumSize(new java.awt.Dimension(250, 350));
        jPanel3.setPreferredSize(new java.awt.Dimension(250, 350));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cardName.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        cardName.setForeground(new java.awt.Color(255, 255, 255));
        cardName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel3.add(cardName, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 140, 20));

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Std ID:");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, 20));

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("DOB :");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, 20));

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Phone no:");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, 20));

        dbId.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        dbId.setForeground(new java.awt.Color(255, 255, 255));
        dbId.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel3.add(dbId, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, 150, 20));

        stdId.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        stdId.setForeground(new java.awt.Color(255, 255, 255));
        stdId.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel3.add(stdId, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 150, 20));

        imgId.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jPanel3.add(imgId, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 130, 130));

        emailId.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        emailId.setForeground(new java.awt.Color(255, 255, 255));
        emailId.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel3.add(emailId, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, 150, 20));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/idcardgenerator/images/1.png"))); // NOI18N
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pPanel.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, -1, 360));

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Blood Grp:");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, 20));

        bldId.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        bldId.setForeground(new java.awt.Color(255, 255, 255));
        bldId.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel4.add(bldId, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 120, 20));

        genId.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        genId.setForeground(new java.awt.Color(255, 255, 255));
        genId.setText("Gender");
        jPanel4.add(genId, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 70, 20));

        gendID.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        gendID.setForeground(new java.awt.Color(255, 255, 255));
        gendID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel4.add(gendID, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 120, 20));

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Address");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 70, 20));

        addID.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        addID.setForeground(new java.awt.Color(255, 255, 255));
        addID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel4.add(addID, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 120, 50));

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Email ID:");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, 20));

        cardBranch.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        cardBranch.setForeground(new java.awt.Color(255, 255, 255));
        cardBranch.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel4.add(cardBranch, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 120, 20));

        cardMob.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        cardMob.setForeground(new java.awt.Color(255, 255, 255));
        cardMob.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel4.add(cardMob, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 120, 20));

        jLabel9.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Branch :");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 50, 20));

        jLabel8.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/idcardgenerator/images/2 (2).png"))); // NOI18N
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pPanel.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 50, 250, 360));

        getContentPane().add(pPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 780, 450));

        jButton1.setBackground(new java.awt.Color(0, 204, 204));
        jButton1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Print");
        jButton1.setToolTipText("");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 490, 210, 60));

        Back.setBackground(new java.awt.Color(204, 0, 0));
        Back.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        Back.setForeground(new java.awt.Color(255, 255, 255));
        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        getContentPane().add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 490, 210, 60));

        pack();
    }// </editor-fold>                        

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        PrinterJob printerJob = PrinterJob.getPrinterJob();
        printerJob.setJobName("Print IdCard");
        
       printerJob.setPrintable(new Printable(){
       
           @Override
           public int print(Graphics graphics, PageFormat pageFormat, int pageIndex)throws PrinterException{
               
                if(pageIndex>0){
                    return Printable.NO_SUCH_PAGE;
                }
                
                Graphics2D graphics2D = (Graphics2D)graphics;
                graphics2D.translate(pageFormat.getImageableX()*2,pageFormat.getImageableY()*2);
                graphics2D.scale(0.5,0.5);
                
                pPanel.paint(graphics2D);
                
                return Printable.PAGE_EXISTS;
                
               
           }
       
       
       });
       
        boolean returningResult = printerJob.printDialog();
        if(returningResult){
            try{
                printerJob.print();
            }
            catch(PrinterException printerException){
                JOptionPane.showMessageDialog(this,"Print Error: "+printerException.getMessage());
            }
        }
        
        
    }                                        

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
        JFrame frame = new JFrame("EXIT");
        if(JOptionPane.showConfirmDialog(frame,"Are you sure you want to go back?","EXIT",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION){
            new Home().setVisible(true);
            
        }

    }                                    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IdCard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IdCard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IdCard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IdCard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new IdCard().setVisible(true);
        });
       
        
    }

    // Variables declaration - do not modify                     
    public static javax.swing.JButton Back;
    public static javax.swing.JLabel addID;
    public static javax.swing.JLabel bldId;
    public static javax.swing.JLabel cardBranch;
    public static javax.swing.JLabel cardMob;
    public static javax.swing.JLabel cardName;
    public static javax.swing.JLabel dbId;
    public static javax.swing.JLabel emailId;
    public static javax.swing.JLabel genId;
    public static javax.swing.JLabel gendID;
    public static javax.swing.JLabel imgId;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel pPanel;
    public static javax.swing.JLabel stdId;
    // End of variables declaration                   
}
